services:
  backend:
    tty: true
    build: ./backend
    # image: molline/yolo-backend:1.0.0
    links:
      - mongodb:mongodb
    ports:
      - "5000:5000"
    command: npm run start
    
  client:
    tty: true
    # build: ./client
    image: molline/yolo-client:1.0.0
    links:
      - mongodb:mongodb
    ports:
      - "3000:3000"
    command: npm start
    
  mongodb:
    image: mongo
    ports:
      - "2701:2701"
    command: systemctl start mongodb





