# # Creating a configMap to reference configurtion variables 
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: yolo-config
# data: 
#   client.image

# Creating services to expose the application
# Creating the backend service
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP
---
# Creating the client service
apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  selector:
    app: client
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
# creating the database service
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
  type: ClusterIP
---
# Creating the backend pod which contains the backend and the database containers
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: molline/yolo-backend:1.0.0
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_URI
              value: mongodb://mongodb:27017/yolomy
          command: ["npm", "run", "start"]
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      volumes:
        - name: mongodb-data
          hostPath:
            path: /data/mongodb
            type: DirectoryOrCreate
---
# Creating the client pod which has the client container
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: molline/yolo-client:1.0.0
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              value: mongodb://mongodb:27017/yolomy
          command: ["npm", "start"]
