# Service to allow ingress traffic
apiVersion: v1
kind: Service
metadata:
  name: yolo
  labels:
    app: client
spec:
  ports:
  - nodePort: 30050
    port: 3000
    protocol: TCP
    # targetport: 3000
  selector:
    app: client
  type: nodePort


